version: "3.7"
services:
  backend:
    container_name: go-p2p-backend-dev
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}/udp"
  gui:
    container_name: go-p2p-gui-dev
    build:
      context: gui
      dockerfile: Dockerfile
    environment:
      - PORT=${GUI_PORT}
    ports:
      - "${GUI_PORT}:${GUI_PORT}"
